name: Repository Dispatch Workflow

on:
  repository_dispatch:
    types: [echo_message_yoshi]

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
          COMMENT: ${{ github.event.client_payload.comment }}
        run: echo "$MESSAGE$COMMENT"
